# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKQA8bOvug3T6rZBR4dPEeupHXOx02jE

Monisha Prashant Jetly

2896661
"""

# Importing all libraries required for Data analysis.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import FileLink

"""<h1> 1. Data Selection <h1>

The dataset represents the total number of graduates in higher education categorized by institution type, gender, local/expat, campus location, and degree level from 2012 to 2019.

Dataset Justification
*   Numeric columns (Example: Bachelors, Diploma, Masters, etc.) are useful in quantitative analysis, whereas object columns (Example: Institution Type, Gender, Local Flags, etc.) help in data segmentation and group wise operations.

*   Understanding higher education trends can help in the development of societies.

*   Study of trends over time in higher education facilitates time-series analysis.

*   Relevant in addressing gender or nationality disparities in education.

The dataset I will be using is readily avaliable from the online source [number_of_graduates_in_higher_education_2012-2019](https://opendata.fcsc.gov.ae/@ministry-education/graduates-higher-education-institution-typegender-nationality-campus-emirate-degree).

<h2>Data Preparation and Exploration<h2>

<h3>Data Import and Cleaning<h3>
"""

# Loading the dataset.
df = pd.read_csv('number_of_graduates_in_higher_education_2012-2019.csv')
# Displaying first 5 records.
df.head()
Acad_year, campus_zone
2012-2013, abu
concat(df['Academic_Year'],',',df['Campus_Zone_EN'])

# prompt: concate academic year and campus zone

import pandas as pd
# ... (rest of your existing code)

# Concatenate 'Academic_Year' and 'Campus_Zone_EN' columns
df['Academic_Year_Campus'] = df['Academic_Year'].astype(str) + '_' + df['Campus_Zone_EN'].astype(str)

# Display the updated DataFrame
print(df.head())

# Dropping column with Arabic values, because the translated version exists in the table as ColName_EN
df.drop(['Institution_Type_AR','Campus_Zone_AR','Local Flag_AR','Gender_AR'],axis='columns', inplace=True)

# Removing spaces in column names for maintaining consistent naming conventions.
df.rename(columns={'Local Flag_EN': 'Local_Flag', 'Graduate Certificate': 'Graduate_Certificate', 'Graduate Diploma': 'Graduate_Diploma','Higher Diploma':'Higher_Diploma'}, inplace=True)
#Displaying the column names
print(df.columns)

# Creating a column 'Start_Year' by splitting the 'Academic_Year' in order to break the range.
df['Start_Year'] = df['Academic_Year'].str.split('-').str[0].astype(int)
# Sorting the dataframe by 'Start_Year'
df = df.sort_values(by='Start_Year')

# Dropping the 'Start_Year' Column as the table is sorted and is no longer required.
df = df.drop(columns=['Start_Year'])

# Displaying first 5 records of the dataframe.
df.head()

# Creating a Backup to avoid corruption of data.
df.to_csv('no_of_grads_copy.csv', index=False)
# Providing a link to download the file
FileLink('no_of_grads_copy.csv')

# Loading the dataset
data = pd.read_csv('no_of_grads_copy.csv')
# Displaying first 5 records.
data.head()

# Handling Missing Values

# Sum of Null Values for every column sorted in descending order
sorted_df = data.isna().sum().sort_values(ascending = False)
sorted_df

"""As the data is specific to programs taken by candidates, there isn't a scenario for missing, incorrect or irrelevant data.`"""

# Handling Duplicate Values

# Displaying the shape of dataframe.
data.shape

# Returns a boolean Series, where True is a duplicate row.
duplicate_values = data[data.duplicated()]

# Displaying a tuple with sum of duplicate values and number of columns(shape).
print('Number of Duplicate Records: ', duplicate_values.shape)

# To handle outliers

Q1 = data['Bachelors'].quantile(0.25)
Q3 = data['Bachelors'].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
data = data[(data['Bachelors'] >= lower_bound) & (data['Bachelors'] <= upper_bound)]
data.shape

# To handle inconsistencies

# Maintaining consistent naming conventions.
data.columns = [col.strip().replace(' ', '_') for col in data.columns]

"""<h3>Exploratory Data Analysis<h3>"""

# Displaying the description of the dataframe
data.describe()

"""Observations


*   **Bachelors**:

Bachelor's degrees have the highest number of graduates (mean = 418.96), with a maximum of 2,992 graduates in a single entry.

This shows that Bachelor's programs are the most common among higher education in the dataset.

*   **Certificate**:

Certificate programs have a much lower count of data points (count = 69) compared to other qualifications, with an average of 20 graduates.

Certificate programs are less prevalent and likely offered by fewer institutions

*   **Diploma**:

Diploma programs have a range of graduate numbers (1 to 532), with a median of 19 graduates.

*   **Doctorate**:

Doctorate programs have the smallest mean graduate count (6.51) and a relatively low maximum of 22 graduates

It is possible that students are unable to meet the requirements for Doctorate programs.

*   **Graduate Certificate**:

Graduate Certificate programs are rare (count = 4), with a mean of 4.25 graduates.

These programs may be new.

*   **Higher Diploma**:

Higher Diploma graduates have a median count of 15.5 but a maximum of 201 graduates.

These programs are moderately popular and could bridge the gap between diplomas and advanced degrees.

*   **Masters**:

Master's degrees have a mean of 125.52 graduates, with some institutions producing up to 1,030 graduates.

Master's programs are popular among students seeking higher education.

*   **Other**:

Has the smallest data count (20) but a high maximum (238), this captures miscellaneous programs.

*   **Total**:

The total number of graduates per entry has a mean of 571.36, with a maximum of 3,204.

This shows some institutions have significantly higher graduate numbers than others.
some very large institutions.

Insights

Bachelor's degrees dominate the dataset in terms of popularity and output.

Specialized programs (e.g., Doctorate, Graduate Certificate) are less common.
"""

# Displaying Information about the dataframe
data.info()

"""Observations

There are 314 records and 16 columns in the dataframe.

Numeric columns (Example: Bachelors, Diploma, Masters, etc.).
Object columns (Example: Institution Type, Gender, Local Flags, etc.).

Missing data in these columns highlights that not all institutions offer or specialized degree programs.
"""

# Displaying the unique values in the 'Campus Zone' column.
zones = data.Campus_Zone_EN.unique()
zones

"""The dataset includes seven campus zones, representing the 7 emirates in the UAE"""

# Univariate Analysis for Numerical Columns

df['Bachelors'].plot(kind='hist', bins=30, figsize=(10, 6), color='lightblue', edgecolor='black')
plt.title('Distribution of Bachelors')
plt.xlabel('Bachelors')
plt.show()

"""Observations

This graphs shows most number of graduates are clustered on the lower end of the scale and very few institutions having high number of graduates in the dataframe.

There is a peak in the lower range of bachelor degree graduates, with over 100 instances where it is close to zero. This shows that most records report a small number of graduates.

Few datapoints towards the right are likely outliers. As it might be a large institution.
"""

# Correlation Heatmap

corr_matrix = df.corr(numeric_only=True)
dataplot = sns.heatmap(corr_matrix, annot=True, cmap='YlGnBu', fmt='.2f')
plt.title('Correlation Matrix')
plt.show()

"""The overall graduate count is strongly influenced by Bachelor's, while specialized programs (Example: Doctorates, Graduate Certificates, etc.) show weak or negative relationships with other programs."""

# Bivariate Analysis - Scatter plot

sns.scatterplot(x='Bachelors', y='Diploma', data=df)
plt.title('Scatter Plot between Bachelors and Diploma')
plt.show()

"""The data shows that most institutions have low numbers of graduates in both categories and few outliers exist with higher numbers of graduates."""

# Categorical vs Numerical - Boxplot

sns.boxplot(x='Academic_Year', y='Bachelors', data=df)
plt.title('Boxplot of Bachelors by Academic_Year')
plt.xticks(rotation=45)
plt.show()

# Pair Plot for Multiple Numerical Variables

sns.pairplot(df[['Bachelors', 'Diploma', 'Masters']])
plt.show()

# Count Plot for Categorical Variables

sns.countplot(x='Academic_Year', data=df)
plt.title('Countplot of Academic_Year')
plt.xticks(rotation=45)
plt.show()

"""<h2>Data Analysis<h2>

<h3> Data Manipulation with Pandas and NumPy <h3>
"""

# Filtering rows where Gender is female
filtered_df = data[data['Gender_EN'] == 'Female']
# Displaying the filtered DataFrame
filtered_df.head()

# Filtering rows where Institution Type is Federal, Zone is Abu Dhabi, and nationality is Expat
filtered_df = data[(data['Institution_Type_EN'] == 'Federal') &
                 (data['Campus_Zone_EN'] == 'Abu Dhabi') &
                 (data['Local_Flag'] == 'Expat')]
# Displaying the filtered DataFrame
filtered_df.head()

# Filtering records where Academic Year starts from '2012'
filtered_df = data[data['Academic_Year'].str.contains('2012', case=False, na=False)]
# Displaying the filtered DataFrame
filtered_df.head()

# Grouping by Gender
gender_totals = data.groupby('Gender_EN')['Total'].sum()
gender_totals

# Grouping by Academic Year
yearly_totals = data.groupby('Academic_Year')['Total'].sum()
yearly_totals

# Calculating Total Bachelors
total_bachelors = data['Bachelors'].sum()
print("Total bachelors:", total_bachelors)

# Calculating mean of Bachelors
mean_bachelors = data['Bachelors'].mean()
print("Mean of Bachelors:", mean_bachelors)

# Count of Locals and Expats
count_by_Localflag_En = data['Local_Flag'].value_counts()
count_by_Localflag_En

# Applying multiple aggregation functions to Bachelors and Diploma
aggregated_df = data.agg({
    'Bachelors': ['mean', 'sum','min', 'max'],
    'Diploma': ['mean', 'sum','min', 'max'],
})
aggregated_df

# Create a pivot table with Zone as rows, Gender as columns, and Bachelors as values
pivot_df = data.pivot_table(values='Bachelors', index='Campus_Zone_EN', columns='Gender_EN', aggfunc='mean')
pivot_df

"""<h3>Feature Engineering<h3>"""

# Binary Feature

# Assuming Candidates is a numerical column
candidate_threshold = 200  # Defining a threshold
data['More_candidates'] = np.where(data['Bachelors']>candidate_threshold, 1,0)

# Displaying the freature.
print(data[['Academic_Year','Campus_Zone_EN','Local_Flag','Bachelors', 'More_candidates']])

"""Assigning 1(True) values to Bachelors having more than 200(threshold) bachelors.

Creation of this feature:
* Provides insight into no.of bachelor graduates in a given academic year, campus zone, and local flag exceeds a certain threshold(200).

* Also helps categorizing institutions, interpretation, analysis and creating predictive models based on number of bachelor graduates.

<h3> Statistical Analysis <h3>
"""

# Descriptive statistics
data.describe()

# Correlation matrix
corr_matrix = data.corr(numeric_only=True)
corr_matrix

"""Observations

* There's a strong correlation between the number of bachelors graduates and the total number of graduates across all degree types. This indicates that institutions with more Bachelors graduates tend to have higher overall graduate numbers.

*  There’s a moderate correlation, showing that institutions with higher number of bachelor graduates often have more master students as well.

*  Larger institutions (higher number of bachelors and total graduates) tend to offer more diverse programs (e.g., Masters, Higher Diplomas, and sometimes Graduate Certificates).

*  Some degree types, like Graduate Certificates and Diplomas, show an inverse relationship, suggesting that they may not coexist well in certain institutions.

<h2> Data Visualization <h2>
"""

# Grouping the data by academic year and adding the total graduates
yearly_totals = data.groupby('Academic_Year')['Total'].sum()
plt.figure(figsize=(12, 6))

#Creating a line plot for yearly totals
sns.lineplot(x=yearly_totals.index, y=yearly_totals.values, marker="o", color="teal")

# Visualisation
plt.title("Total Graduates Over Academic Years")
plt.xlabel("Academic Year")
plt.ylabel("Total Graduates")
plt.xticks(rotation=45)
plt.grid(axis="y", linestyle="--", alpha=0.7)
plt.show()

"""Observations
* Displays total number of graduates per academic year.
* In the academic year 2018-2019, there has been a fall after the rise in 2017-2018. This could be possible due to unknown factors or extra features missing from the data.
"""

# Grouping the data by Campus Zone and Gender, then summation of graduates
grouped_df = data.groupby(['Campus_Zone_EN', 'Gender_EN'])['Bachelors'].sum().reset_index()

# Creating a bar plot to display the sum of bachelors by Zone and Gender
plt.figure(figsize=(10, 6))
sns.barplot(x='Campus_Zone_EN', y='Bachelors', hue='Gender_EN', data=grouped_df)

# Visualisation
plt.title('Total Bachelors by Campus and Gender', fontsize=16)
plt.xlabel('Campus', fontsize=12)
plt.ylabel('Total of Bachelors', fontsize=12)
plt.legend()
plt.show()

"""Observations
* The dataset represents the number of male and female bachelor graduates in various campuses across the United Arab Emirates (UAE).
* There are more female bachelor graduates compared to the male bachelor graduates in all emirates, excluding Abu Dhabi.

"""

# Grouping the data by Campus Zone and adding the counts for all columns
grouped_df = data.groupby(['Campus_Zone_EN'])[['Bachelors',  'Doctorate','Diploma',
                                              'Graduate_Certificate', 'Graduate_Diploma',
                                              'Higher_Diploma','Certificate', 'Masters', 'Other']].sum().reset_index()

# Sum of total graduates across all zones
total_graduates = grouped_df[['Bachelors', 'Doctorate', 'Diploma',
                              'Graduate_Certificate', 'Graduate_Diploma',
                              'Higher_Diploma', 'Certificate','Masters', 'Other']].sum()

# Plotting Pie Chart
plt.figure(figsize=(7,10))
plt.pie(total_graduates, labels=total_graduates.index, autopct='%1.1f%%', startangle=90)

# Visualisation
plt.title('Distribution of Candidates Across All Campus Zones', fontsize=14)
plt.axis('equal')
plt.legend(loc='lower right')
plt.show()

"""Observations
* Bachelors are significantly greater than any other program.
* Followed by Masters and Diplomas.

<h2>Conclusions and Recommendations<h2>

<h3>Conclusions<h3>

* Bachelor graduates make up a significant portion of the total graduate population, while other categories like Masters, Diplomas, and Doctorates make up for smaller but notable portions. This shows that the majority of graduates from these institutions are pursuing undergraduate degrees (i.e., Bachelors), with Masters and Diplomas following.

* The analysis also suggested that certain Campus Zones might be more dominant in specific categories. For instance, larger urban campuses might see more graduates in Bachelors programs, while specialized campuses or those with a focus on postgraduate education may have a higher proportion of Masters or Doctorate graduates.

* Programs like Graduate Certificates, Higher Diplomas, and Others contributed to smaller amounts, which suggests that these programs are not widely taken as Bachelors and Masters.

<h3> Recommendations <h3>

* Institutions should consider strengthening their postgraduate programs. Encouraging students to pursue Masters or Doctorates. As this could enhance the value of education, especially in fields that require advanced qualifications.

* Campuses with lower graduates from Masters or Doctorate programs should consider introducing more diverse or flexible options (e.g., online, part-time) for working professionals or international students.

* Programs such as Graduate Certificates and Higher Diplomas are more specialized and should be more specific to industry needs. Institutions could collaborate with companies to design programs that provide practical and in-demand skills.

* Campuses with high no.of graduate types (e.g., Bachelors) should target marketing campaigns to attract students for more specialized or advanced degrees.

<h3>Challenges<h3>

1. Handling Missing Values:
   * Several columns contained missing values which could effect statistical calculations and visualisations. Some columns had extremely sparse data.
   * Decision was made to not handle missing values. This ensured the original data was preserved.
2. Data Visualisation:
   * Selecting effective graphs that were visually appealing and easy to interpret took time.
   * Graphs had labeled axes, titles, and legends.
3. Time Management:
   * Dataset selection and cleaning consumed significant time, leaving less time for analysis, visualisation and documentation.
   * In future projects, allocation more time for dataset selection and cleaning would be a priority.
"""
